repository_type: pipeline
nf_core_version: "2.14.1"
lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
modules_config: False
files_unchanged:
  - LICENSE
  - assets/nf-core-rnadnavar_logo_light.png
  - docs/images/nf-core-rnadnavar_logo_dark.png
  - docs/images/nf-core-rnadnavar_logo_light.png
schema_params: False
template_strings: False
multiqc_config: False
