bump_version: null
lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Raquel Manzano-Garcia
  description: Pipeline for RNA and DNA integrated analysis for somatic mutation detection
  force: false
  is_nfcore: true
  name: rnadnavar
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
