name: vcffilter
description: VCF filter the specified vcf file using the set of filters

keywords:
  - VCF
  - filter
  - variant calling
tools:
  - vcffilter:
      description: VCF filter the specified vcf file using the set of filters
      homepage: https://github.com/vcflib/vcflib
      documentation: https://github.com/vcflib/vcflib
      tool_dev_url: https://github.com/vcflib/vcflib
      doi: https://doi.org/10.1101/2021.05.21.445151
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: vcf file (optional)
      pattern: "*.vcf.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: vcf file (optional)
      pattern: "*.vcf.gz"

authors:
  - "@RaqManzano"
