name: vt_normalise
description: normalise VCF files
keywords:
  - normalise
  - VCF
  - variant calling
tools:
  - decompose:
      description: normalise variants in a VCF file.
      homepage: https://genome.sph.umich.edu/wiki/Vt
      documentation: https://genome.sph.umich.edu/wiki/Vt
      tool_dev_url: https://github.com/atks/vt
      doi: "https://doi.org/10.1093/bioinformatics/btv112"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: The VCF/BCF file to be normalised
      pattern: "*.{vcf.gz,vcf,bcf}"
  - meta1:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input genome fasta file

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: normalised VCF file
      pattern: "*.{vcf.gz}"

authors:
  - "@RaqManzano"
